extensions:
- selva.ext.data.sqlalchemy
- selva.ext.templates.jinja

middleware:
- application.middleware.TodoFilterMiddleware

data:
  sqlalchemy:
    connections:
      default:
        url: sqlite+aiosqlite:///db.sqlite3